image: ubuntu

install:
- cd modules/Math-GrahamFunction/
- perl Build.PL
- ./Build installdeps

test_script:
- cd modules/Math-GrahamFunction/
- perl Build.PL
- ./Build
- ./Build test
- ./Build disttest
build: off
