image: ubuntu

install:
- sudo apt-get -y install libclass-accessor-perl libmodule-build-perl

test_script:
- cd modules/Math-GrahamFunction/
- perl Build.PL
- ./Build
- ./Build test
- ./Build disttest
build: off
